# docker-compose.yml
version: "3.8"
services:
  ros_dev_env:
    container_name: "ros-dev-vm"
    image: "noetic-ros-core-focal"
    build: ./
    volumes:
      - ${ROS_PROJECT_PATH}:/ros_ws/src/
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    stdin_open: true
    tty: true
  novnc:
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=2560
      - DISPLAY_HEIGHT=1440
    ports:
      - "8080:8080"
    networks:
      - x11
    restart: on-failure
networks:
  x11:
